[2025-04-15T09:16:55.347-0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-15T09:16:55.351-0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: multi_city_weather_pipeline.fetch_weather_multiple_cities scheduled__2025-04-14T23:00:00+00:00 [queued]>
[2025-04-15T09:16:55.352-0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: multi_city_weather_pipeline.fetch_weather_multiple_cities scheduled__2025-04-14T23:00:00+00:00 [queued]>
[2025-04-15T09:16:55.352-0500] {taskinstance.py:2867} INFO - Starting attempt 7 of 2
[2025-04-15T09:16:55.356-0500] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): fetch_weather_multiple_cities> on 2025-04-14 23:00:00+00:00
[2025-04-15T09:16:55.358-0500] {standard_task_runner.py:72} INFO - Started process 2924 to run task
[2025-04-15T09:16:55.363-0500] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'multi_city_weather_pipeline', 'fetch_weather_multiple_cities', 'scheduled__2025-04-14T23:00:00+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/weather_pipeline_dag.py', '--cfg-path', '/var/folders/4n/q_76d_d57mb9q1qtrf4mvh940000gn/T/tmpr_rc9m1k']
[2025-04-15T09:16:55.364-0500] {standard_task_runner.py:105} INFO - Job 55: Subtask fetch_weather_multiple_cities
[2025-04-15T09:16:55.379-0500] {task_command.py:467} INFO - Running <TaskInstance: multi_city_weather_pipeline.fetch_weather_multiple_cities scheduled__2025-04-14T23:00:00+00:00 [running]> on host ramyas-macbook-air.local
[2025-04-15T09:16:55.398-0500] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='multi_city_weather_pipeline' AIRFLOW_CTX_TASK_ID='fetch_weather_multiple_cities' AIRFLOW_CTX_EXECUTION_DATE='2025-04-14T23:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='7' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-14T23:00:00+00:00'
[2025-04-15T09:16:55.398-0500] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-15T09:16:55.398-0500] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-15T09:16:55.399-0500] {logging_mixin.py:190} INFO - Current task name:fetch_weather_multiple_cities state:running start_date:2025-04-15 14:16:55.351337+00:00
[2025-04-15T09:16:55.399-0500] {logging_mixin.py:190} INFO - Dag name:multi_city_weather_pipeline and current dag run status:running
[2025-04-15T09:16:55.399-0500] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-15T09:31:31.138-0500] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-04-15T09:31:31.143-0500] {process_utils.py:132} INFO - Sending 15 to group 2924. PIDs of all processes in the group: [2924]
[2025-04-15T09:31:31.143-0500] {process_utils.py:87} INFO - Sending the signal 15 to group 2924
[2025-04-15T09:31:35.777-0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-15T09:31:35.783-0500] {taskinstance.py:2604} INFO - Dependencies not met for <TaskInstance: multi_city_weather_pipeline.fetch_weather_multiple_cities scheduled__2025-04-14T23:00:00+00:00 [running]>, dependency 'Task Instance State' FAILED: Task is in the 'running' state.
[2025-04-15T09:31:35.784-0500] {taskinstance.py:2604} INFO - Dependencies not met for <TaskInstance: multi_city_weather_pipeline.fetch_weather_multiple_cities scheduled__2025-04-14T23:00:00+00:00 [running]>, dependency 'Task Instance Not Running' FAILED: Task is in the running state
[2025-04-15T09:31:35.784-0500] {local_task_job_runner.py:166} INFO - Task is not able to be run
