[2025-04-14T18:53:29.275-0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-14T18:53:29.278-0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_weather_pipeline.fetch_weather_dallas scheduled__2025-04-14T22:00:00+00:00 [queued]>
[2025-04-14T18:53:29.280-0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_weather_pipeline.fetch_weather_dallas scheduled__2025-04-14T22:00:00+00:00 [queued]>
[2025-04-14T18:53:29.280-0500] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-14T18:53:29.283-0500] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): fetch_weather_dallas> on 2025-04-14 22:00:00+00:00
[2025-04-14T18:53:29.285-0500] {standard_task_runner.py:72} INFO - Started process 96277 to run task
[2025-04-14T18:53:29.288-0500] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'daily_weather_pipeline', 'fetch_weather_dallas', 'scheduled__2025-04-14T22:00:00+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/weather_pipeline_dag.py', '--cfg-path', '/var/folders/4n/q_76d_d57mb9q1qtrf4mvh940000gn/T/tmpx99jo90i']
[2025-04-14T18:53:29.289-0500] {standard_task_runner.py:105} INFO - Job 26: Subtask fetch_weather_dallas
[2025-04-14T18:53:29.305-0500] {task_command.py:467} INFO - Running <TaskInstance: daily_weather_pipeline.fetch_weather_dallas scheduled__2025-04-14T22:00:00+00:00 [running]> on host ramyas-macbook-air.local
[2025-04-14T18:53:29.326-0500] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='daily_weather_pipeline' AIRFLOW_CTX_TASK_ID='fetch_weather_dallas' AIRFLOW_CTX_EXECUTION_DATE='2025-04-14T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-14T22:00:00+00:00'
[2025-04-14T18:53:29.327-0500] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-14T18:53:29.327-0500] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-14T18:53:29.327-0500] {logging_mixin.py:190} INFO - Current task name:fetch_weather_dallas state:running start_date:2025-04-14 23:53:29.278924+00:00
[2025-04-14T18:53:29.327-0500] {logging_mixin.py:190} INFO - Dag name:daily_weather_pipeline and current dag run status:running
[2025-04-14T18:53:29.327-0500] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-14T18:55:07.475-0500] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-04-14T18:55:07.482-0500] {process_utils.py:132} INFO - Sending 15 to group 96277. PIDs of all processes in the group: [96277]
[2025-04-14T18:55:07.482-0500] {process_utils.py:87} INFO - Sending the signal 15 to group 96277
[2025-04-14T18:55:09.645-0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-14T18:55:09.650-0500] {taskinstance.py:2604} INFO - Dependencies not met for <TaskInstance: daily_weather_pipeline.fetch_weather_dallas scheduled__2025-04-14T22:00:00+00:00 [running]>, dependency 'Task Instance Not Running' FAILED: Task is in the running state
[2025-04-14T18:55:09.650-0500] {taskinstance.py:2604} INFO - Dependencies not met for <TaskInstance: daily_weather_pipeline.fetch_weather_dallas scheduled__2025-04-14T22:00:00+00:00 [running]>, dependency 'Task Instance State' FAILED: Task is in the 'running' state.
[2025-04-14T18:55:09.650-0500] {local_task_job_runner.py:166} INFO - Task is not able to be run
